apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-edge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-edge
  template:
    metadata:
      labels:
        app: project-edge
    spec:
      containers:
      - name: project-edge-container
        image: edge-app:latest
        ports:
        - containerPort: 8000
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ADDRESS
            value: "$(POD_IP):8000"
